### ISSUE TITLE
Enhance catalog app services

### ISSUE THREAD

**Issue by dano-reisys** [GSA/catalog-app#15]
- [x] refactor postgres dockerfile to use datacats postgres dockerfile elements #16
- [x] refactor solr dockerfile to use datacats solr dockerfile elements #17
- [ ] refactor web dockerfile to use nginx #7
