### ISSUE TITLE
refactor main Dockerfile (app)

### ISSUE THREAD

**Issue by dano-reisys** [GSA/catalog-app#2]
To Do: 
- [x] refactor entrypoint.sh in order to be able to start paster commands  (i.e. harvester-fetch, harvester-gather, qa update, qa-update sel) #12 
- [x] create fgdc2iso conversion docker image (separate service) #13 
- [ ]  figure out the best way to handle cron jobs through docker containers #14 

Separate the application from the harvester. The harvester should have its own dockerfile or maybe two? harvester-fetch & harvester-gather 

> Run only one process per container
> In almost all cases, you should only run a single process in a single container. Decoupling applications > into multiple containers makes it much easier to scale horizontally and reuse containers. If that service > depends on another service, make use of container linking.

Both harvester-fetch & harvester-gather processes run through supervisor

https://github.com/GSA/catalog-app/blob/master/docker/webserver/supervisor/supervisord.conf

**Comment by JJediny** [comment]
Used this cmd to copy the contents of the lock file on the db:

     sudo docker cp catalogapp_db_1:/run/postgresql/.s.PGSQL.5432.lock /home/jjediny/Desktop/db_lock.txt

Contents of it pasted here...
>1
/var/lib/postgresql/9.3/main
1450159301
5432
/var/run/postgresql

However accessing the db container and reading postgresql-9.3-main.log doesn't indicate an error in the connection nor an open connection error...

>2015-12-15 02:56:48 UTC LOG:  database system was shut down at 2015-11-24 03:55:43 UTC
2015-12-15 02:56:48 UTC LOG:  MultiXact member wraparound protections are now enabled
2015-12-15 02:56:48 UTC LOG:  autovacuum launcher started
2015-12-15 02:56:48 UTC LOG:  database system is ready to accept connections
2015-12-15 02:56:48 UTC LOG:  incomplete startup packet

**Comment by JJediny** [comment]
To Do:
- [ ] harvest-fetch & harvest-gather (need to be started automatically w/ `supervisorctl start harvest-fetch`
- [ ] Add crond to dependenceis (for cron jobs responsible for initiating/running harvest jobs

**Comment by dano-reisys** [comment]
dockerfiles for harvesters should be straight forward (we need to declare the required packages + any config options) @FuhuXia would be able to help as well.

we might also explore the possibility of using systemd (@fxia) for cronjobs.

**Comment by dano-reisys** [comment]
Looks like there is a fgdc2iso conversion process (war app that runs through tomcat). This should most probably go into another container @FuhuXia

**Comment by JJediny** [comment]
@dano-reisys @philipashlock @alex-perfilov-reisys @FuhuXia ... Whiteboard session - goal to determine the baseline image of CKAN that can then be inheritated expanded on for catalog/harvester/inventory

![image](https://cloud.githubusercontent.com/assets/6350035/11883295/eb74f0a2-a4df-11e5-83b9-188f902ee7d0.png)

**Comment by dano-reisys** [comment]
Unanswered questions from yesterday:

1. What extensions are shared between inventory and catalog? (@FuhuXia)
2. How does the datapusher work?
http://docs.ckan.org/projects/datapusher/en/latest/
https://github.com/ckan/datapusher/issues/18
3. How does the qa extension work?
https://github.com/ckan/ckanext-qa
REI has create another paster command for this extension: https://github.com/GSA/ckanext-qa/blob/2.3-upgrade/ckanext/qa/commands.py#L31
I believe that this is what is being used in prod (@FuhuXia do you have any more comments?)

Info on the harvesting process: https://github.com/ckan/ckanext-harvest

**Comment by FuhuXia** [comment]
1. ckanext-datajson is the only ext that both catalog and inventory shares. For quite a while the extension has two flavors, one for catalog one for inventory, then the codes are merged into same branch, but plugins remain separated. Catalog and inventory have their own set of plugin to enable.

2. I think its readme explains well for datapusher:
>DataPusher is a standalone web service that automatically downloads any CSV or XLS (Excel) data files from a CKAN site's resources when they are added to the CKAN site, parses them to pull out the actual data, then uses the DataStore API to push the data into the CKAN site's DataStore.
>
>This makes the data from the resource files available via CKAN's DataStore API.

3. We run both `qa update_sel` and `qa update`, one on daily basis for newly created/updated packages, one on quarterly/manual basis for a complete re-check, which take days, or even weeks, to complete.
